# Rules needed: all, httpserver, clean
# 	which produce the httpserver binary
# 	
# 	clean should remove all .o and binary files

TARGETS=

CC=clang

CFLAGS=-Wall -Wextra -Werror -pedantic


.PHONY: all
all: $(TARGETS)


.PHONY: clean
clean:
	rm -f *.o


# Reminder:
# targets : prereqs
# 	commands
